### ISSUE TITLE
ошибка при вызове в шаблоне

### ISSUE THREAD

**Issue by andrewt82** [aruseni/chat#2]
выдается ошибка NoReverseMatch at /messages/
Exception Value:  
Reverse for '' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

ругается на chat/myproject/templates/private_messages.html, error at line 15
{% url privatemessages.views.send_message_view %}

в чем может быть причина?

**Comment by aruseni** [comment]
Это вам надо кавычки добавить. Такой синтаксис с Django 1.5 уже не
поддерживается.
